[QI2-1223] Call reusable authentication script for e2e
QuTech-Delft/qiskit-quantuminspire pull request #81
Opened 2024-12-04 21:02 UTC by oschusler

2024-12-20 15:22 UTC, eliasKA requested changes

2024-12-20 15:22 UTC, eliasKA commented on .github/workflows/tests.yaml
> +          cat ~/.quantuminspire/config.json
Why are we doing the `cat` here? Do we want to expose this data in the action logs?

2024-12-20 15:22 UTC, eliasKA commented on .github/workflows/tests.yaml
> +          cat ~/.quantuminspire/config.json
No need to do it here again if we're doing it in the previous step already WDYT?

2024-12-23 10:30 UTC, NischalQuTech commented on tests/e2e_test.py
> +    # _get_auth_tokens()
commented out code ?

2024-12-23 10:31 UTC, NischalQuTech commented on .github/workflows/tests.yaml
> +      QI2_default_host: https://staging.qi2.quantum-inspire.com
are we planning to keep this hardcoded here or is this supposed to be derived from secrets ?

2024-12-23 10:36 UTC, closed without merging